// AUTO-GENERATED — DO NOT EDIT BY HAND.
//
// Generated by website/scripts/generate-op-reference.mjs from the LoreGUI
// command-palette manifests (frontend/src/palette/manifest/<domain>/<op>.ts),
// the single source of truth for the op surface. Regenerate with:
//   npm --prefix website run generate:ops
// It also runs automatically via the predev / prebuild npm hooks.

export interface OpArg {
  name: string;
  label: string;
  /** Human-readable type, e.g. "string", "number", "enum(local | s3)". */
  type: string;
  description: string;
  required: boolean;
}

export interface OpReferenceEntry {
  /** Stable id "<domain>.<op>". */
  id: string;
  op: string;
  label: string;
  description: string;
  /** The Tauri command the palette invokes. */
  command: string;
  /** Where the op lives in the app: "panel" | "menu" | "palette". */
  surface: string;
  resultKind: string;
  args: OpArg[];
}

export interface OpReferenceGroup {
  domain: string;
  blurb: string;
  ops: OpReferenceEntry[];
}

/** Total ops documented across all domains. */
export const OP_COUNT = 110;

/** Number of domains documented. */
export const DOMAIN_COUNT = 12;

export const OP_REFERENCE: OpReferenceGroup[] = [
  {
    "domain": "auth",
    "blurb": "Identity and sign-in: log in to a server, inspect the current user, and log out.",
    "ops": [
      {
        "id": "auth.clear",
        "op": "clear",
        "label": "Auth: Clear all sessions",
        "description": "Clear all locally stored auth sessions on this device.",
        "command": "auth_clear",
        "surface": "palette",
        "resultKind": "void",
        "args": []
      },
      {
        "id": "auth.local_user_info",
        "op": "local_user_info",
        "label": "Auth: Local User Info",
        "description": "Resolve user identities from locally cached JWT tokens.",
        "command": "auth_local_user_info",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "authEndpoint",
            "label": "Auth Endpoint",
            "type": "string",
            "description": "",
            "required": false
          },
          {
            "name": "userIds",
            "label": "User IDs",
            "type": "string[]",
            "description": "",
            "required": false
          },
          {
            "name": "withToken",
            "label": "With Token",
            "type": "boolean",
            "description": "",
            "required": false
          }
        ]
      },
      {
        "id": "auth.login_interactive",
        "op": "login_interactive",
        "label": "Auth: Login (Interactive)",
        "description": "Authenticate against a remote via browser-based OAuth flow. Returns user identity on success.",
        "command": "auth_login_interactive",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "remoteUrl",
            "label": "Remote URL",
            "type": "string",
            "description": "Remote API URL; empty resolves from the repository config.",
            "required": false
          }
        ]
      },
      {
        "id": "auth.login_with_token",
        "op": "login_with_token",
        "label": "Auth: Login with Token",
        "description": "Authenticate against a remote using a bearer token, without a browser; returns the signed-in user.",
        "command": "auth_login_with_token",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "remoteUrl",
            "label": "Remote URL",
            "type": "string",
            "description": "Remote API URL to authenticate against.",
            "required": true
          },
          {
            "name": "token",
            "label": "Token",
            "type": "string",
            "description": "Bearer token to authenticate with.",
            "required": true
          }
        ]
      },
      {
        "id": "auth.logout",
        "op": "logout",
        "label": "Auth: Sign out",
        "description": "Sign out of a server, clearing its stored session.",
        "command": "auth_logout",
        "surface": "palette",
        "resultKind": "void",
        "args": [
          {
            "name": "authUrl",
            "label": "Server URL",
            "type": "string",
            "description": "",
            "required": true
          },
          {
            "name": "resource",
            "label": "Resource",
            "type": "string",
            "description": "",
            "required": false
          },
          {
            "name": "userId",
            "label": "User ID",
            "type": "string",
            "description": "",
            "required": false
          }
        ]
      },
      {
        "id": "auth.resolve_user_info",
        "op": "resolve_user_info",
        "label": "Auth: Resolve User Info",
        "description": "Resolve the currently authenticated user's ID and display name.",
        "command": "auth_user_info",
        "surface": "palette",
        "resultKind": "json",
        "args": []
      }
    ]
  },
  {
    "domain": "branch",
    "blurb": "Create, switch, protect, reset, and archive branches, and drive the guided three-way merge state machine.",
    "ops": [
      {
        "id": "branch.archive",
        "op": "archive",
        "label": "Branch: Archive",
        "description": "Archives a branch locally and on the remote, preventing further commits.",
        "command": "branch_archive",
        "surface": "palette",
        "resultKind": "text",
        "args": [
          {
            "name": "branch",
            "label": "Branch",
            "type": "string",
            "description": "The branch name to archive.",
            "required": true
          }
        ]
      },
      {
        "id": "branch.create",
        "op": "create",
        "label": "Branch: Create",
        "description": "Create a new branch, optionally under a category and with an explicit branch id.",
        "command": "branch_create",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "branch",
            "label": "Branch name",
            "type": "string",
            "description": "Name of the branch to create.",
            "required": true
          },
          {
            "name": "category",
            "label": "Category",
            "type": "string",
            "description": "Optional branch category (e.g. main, dev).",
            "required": false
          },
          {
            "name": "id",
            "label": "Branch id",
            "type": "string",
            "description": "Optional explicit branch id (hex-encoded 16-byte context); leave empty to auto-generate.",
            "required": false
          }
        ]
      },
      {
        "id": "branch.info",
        "op": "info",
        "label": "Branch: Info",
        "description": "Show metadata for a branch — name, category, parent, creator, timestamps, and archive state.",
        "command": "branch_info",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "branch",
            "label": "Branch",
            "type": "string",
            "description": "Branch name; leave empty for the current branch.",
            "required": false
          }
        ]
      },
      {
        "id": "branch.latest_list",
        "op": "latest_list",
        "label": "Branch: Latest List",
        "description": "List the latest revision history for a branch (newest first).",
        "command": "branch_latest_list",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "branch",
            "label": "Branch",
            "type": "string",
            "description": "Branch name; empty for current branch.",
            "required": false
          },
          {
            "name": "limit",
            "label": "Limit",
            "type": "number",
            "description": "Maximum entries to return; 0 uses the default of 30.",
            "required": false
          }
        ]
      },
      {
        "id": "branch.list",
        "op": "list",
        "label": "Branch: List",
        "description": "List all branches in the repository, optionally including archived branches.",
        "command": "branch_list",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "archived",
            "label": "Include archived",
            "type": "boolean",
            "description": "When enabled, archived branches are included in the listing.",
            "required": false
          }
        ]
      },
      {
        "id": "branch.merge",
        "op": "merge",
        "label": "Branch: Merge",
        "description": "Merge a named branch into the current branch.",
        "command": "merge_branch",
        "surface": "palette",
        "resultKind": "void",
        "args": [
          {
            "name": "name",
            "label": "Branch",
            "type": "string",
            "description": "Name of the branch to merge into the current branch.",
            "required": true
          }
        ]
      },
      {
        "id": "branch.merge_abort",
        "op": "merge_abort",
        "label": "Branch: Abort Merge",
        "description": "Abort an in-progress branch merge, discarding its staged merge state.",
        "command": "branch_merge_abort",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "link",
            "label": "Link",
            "type": "string",
            "description": "Merge link identifier to abort.",
            "required": false
          },
          {
            "name": "ignoreLinks",
            "label": "Ignore links",
            "type": "boolean",
            "description": "Ignore link records while aborting.",
            "required": false
          }
        ]
      },
      {
        "id": "branch.merge_into",
        "op": "merge_into",
        "label": "Branch: Merge Into",
        "description": "Merge the current branch into a specified target branch with a commit message.",
        "command": "branch_merge_into",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "branch",
            "label": "Target branch",
            "type": "string",
            "description": "Branch to merge the current branch into.",
            "required": true
          },
          {
            "name": "branchId",
            "label": "Target branch id",
            "type": "string",
            "description": "Optional explicit id of the target branch.",
            "required": false
          },
          {
            "name": "message",
            "label": "Message",
            "type": "string",
            "description": "Commit message for the merge.",
            "required": false
          },
          {
            "name": "link",
            "label": "Link",
            "type": "string",
            "description": "Optional merge link identifier.",
            "required": false
          },
          {
            "name": "ignoreLinks",
            "label": "Ignore links",
            "type": "boolean",
            "description": "Ignore link records during the merge.",
            "required": false
          }
        ]
      },
      {
        "id": "branch.merge_resolve",
        "op": "merge_resolve",
        "label": "Branch: Merge Resolve",
        "description": "Mark conflicted files as resolved during an in-progress merge.",
        "command": "branch_merge_resolve",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "paths",
            "label": "Paths",
            "type": "string[]",
            "description": "Conflicted file paths to mark as resolved.",
            "required": false
          }
        ]
      },
      {
        "id": "branch.merge_resolve_mine",
        "op": "merge_resolve_mine",
        "label": "Branch: Merge Resolve Mine",
        "description": "Resolve merge conflicts by accepting the local (mine) version for the specified paths.",
        "command": "branch_merge_resolve_mine",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "paths",
            "label": "Paths",
            "type": "string[]",
            "description": "File paths to resolve using the local version (one per line).",
            "required": false
          }
        ]
      },
      {
        "id": "branch.merge_resolve_theirs",
        "op": "merge_resolve_theirs",
        "label": "Branch: Resolve Merge (Theirs)",
        "description": "Resolve conflicts on the given paths by taking the incoming (theirs) version.",
        "command": "branch_merge_resolve_theirs",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "paths",
            "label": "Paths",
            "type": "string[]",
            "description": "Conflicted paths to resolve as theirs (one per line).",
            "required": true
          }
        ]
      },
      {
        "id": "branch.merge_restart",
        "op": "merge_restart",
        "label": "Branch: Restart Merge Resolution",
        "description": "Restart conflict resolution for the given paths in an in-progress branch merge.",
        "command": "branch_merge_restart",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "paths",
            "label": "Paths",
            "type": "string[]",
            "description": "Paths to restart merge resolution for (one per line).",
            "required": true
          }
        ]
      },
      {
        "id": "branch.merge_start",
        "op": "merge_start",
        "label": "Branch: Start Merge",
        "description": "Begin merging another branch into the current branch, optionally committing the result.",
        "command": "branch_merge_start",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "branch",
            "label": "Source branch",
            "type": "string",
            "description": "Branch to merge into the current branch.",
            "required": true
          },
          {
            "name": "message",
            "label": "Message",
            "type": "string",
            "description": "Commit message for the merge.",
            "required": false
          },
          {
            "name": "noCommit",
            "label": "No commit",
            "type": "boolean",
            "description": "Stage the merge without creating a commit.",
            "required": false
          },
          {
            "name": "link",
            "label": "Link",
            "type": "string",
            "description": "Optional merge link identifier.",
            "required": false
          },
          {
            "name": "ignoreLinks",
            "label": "Ignore links",
            "type": "boolean",
            "description": "Ignore link records during the merge.",
            "required": false
          }
        ]
      },
      {
        "id": "branch.merge_unresolve",
        "op": "merge_unresolve",
        "label": "Branch: Unresolve Merge Conflicts",
        "description": "Mark files as unresolved during a merge, reverting previous conflict resolutions.",
        "command": "branch_merge_unresolve",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "paths",
            "label": "Files to unresolve",
            "type": "string[]",
            "description": "Paths to mark as unresolved (empty = all conflicted files)",
            "required": false
          }
        ]
      },
      {
        "id": "branch.metadata_get",
        "op": "metadata_get",
        "label": "Branch: Get Metadata",
        "description": "Read the metadata value stored on a branch under a given key.",
        "command": "branch_metadata_get",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "branch",
            "label": "Branch",
            "type": "string",
            "description": "Branch whose metadata to read.",
            "required": true
          },
          {
            "name": "key",
            "label": "Key",
            "type": "string",
            "description": "Metadata key to read.",
            "required": true
          }
        ]
      },
      {
        "id": "branch.protect",
        "op": "protect",
        "label": "Branch: Protect",
        "description": "Apply write protection to a branch, preventing direct commits.",
        "command": "branch_protect",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "branch",
            "label": "Branch",
            "type": "string",
            "description": "Name of the branch to protect.",
            "required": true
          }
        ]
      },
      {
        "id": "branch.reset",
        "op": "reset",
        "label": "Branch: Reset",
        "description": "Reset the local LATEST pointer of a branch to a specific revision.",
        "command": "branch_reset",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "revision",
            "label": "Revision",
            "type": "string",
            "description": "Revision to reset the branch to.",
            "required": true
          },
          {
            "name": "branch",
            "label": "Branch",
            "type": "string",
            "description": "Branch to reset; leave empty for the current branch.",
            "required": false
          }
        ]
      },
      {
        "id": "branch.switch",
        "op": "switch",
        "label": "Branch: Switch",
        "description": "Switch the working tree to a different branch.",
        "command": "switch_branch",
        "surface": "palette",
        "resultKind": "void",
        "args": [
          {
            "name": "name",
            "label": "Branch",
            "type": "string",
            "description": "Name of the branch to switch to.",
            "required": true
          }
        ]
      },
      {
        "id": "branch.unprotect",
        "op": "unprotect",
        "label": "Branch: Unprotect",
        "description": "Remove write protection from a branch, re-allowing direct commits.",
        "command": "branch_unprotect",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "branch",
            "label": "Branch",
            "type": "string",
            "description": "The branch name to unprotect.",
            "required": true
          }
        ]
      }
    ]
  },
  {
    "domain": "dependency",
    "blurb": "Track and edit the links between a file and the assets it references.",
    "ops": [
      {
        "id": "dependency.add",
        "op": "add",
        "label": "Dependency: Add",
        "description": "Add file dependencies to the current repository with optional tags.",
        "command": "dependency_add",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "sources",
            "label": "Sources (JSON)",
            "type": "string",
            "description": "JSON array of {path, dependencies: [{dependency, tags}]}. Example: [{\"path\":\"a.txt\",\"dependencies\":[{\"dependency\":\"b.txt\",\"tags\":[\"texture\"]}]}]",
            "required": true
          },
          {
            "name": "force",
            "label": "Force",
            "type": "boolean",
            "description": "Skip cycle detection.",
            "required": false
          }
        ]
      },
      {
        "id": "dependency.list",
        "op": "list",
        "label": "Dependency: List",
        "description": "List file dependencies or dependents at a given revision.",
        "command": "dependency_list",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "paths",
            "label": "Paths",
            "type": "string[]",
            "description": "File paths to query dependencies for.",
            "required": true
          },
          {
            "name": "revision",
            "label": "Revision",
            "type": "string",
            "description": "Revision to query at; empty for current.",
            "required": false
          },
          {
            "name": "recursive",
            "label": "Recursive",
            "type": "boolean",
            "description": "Follow transitive dependencies recursively.",
            "required": false
          },
          {
            "name": "reverse",
            "label": "Reverse (Dependents)",
            "type": "boolean",
            "description": "Return dependents (reverse lookup) instead of dependencies.",
            "required": false
          },
          {
            "name": "tags",
            "label": "Tags",
            "type": "string[]",
            "description": "Filter results by these tags.",
            "required": false
          },
          {
            "name": "depthLimit",
            "label": "Depth Limit",
            "type": "number",
            "description": "Maximum recursion depth; 0 for unlimited.",
            "required": false
          }
        ]
      },
      {
        "id": "dependency.remove",
        "op": "remove",
        "label": "Dependency: Remove",
        "description": "Remove file dependencies (or specific tags) from the current repository.",
        "command": "dependency_remove",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "sources",
            "label": "Sources (JSON)",
            "type": "string",
            "description": "JSON array of {path, dependencies: [{dependency, tags}]}. Empty tags removes the entire edge. Example: [{\"path\":\"a.txt\",\"dependencies\":[{\"dependency\":\"b.txt\"}]}]",
            "required": true
          }
        ]
      }
    ]
  },
  {
    "domain": "file",
    "blurb": "Stage, unstage, diff, hash, and inspect files, plus per-file history and dependency edits.",
    "ops": [
      {
        "id": "file.diff",
        "op": "diff",
        "label": "File: Diff",
        "description": "Compute unified diff between two revisions.",
        "command": "file_diff",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "paths",
            "label": "Paths",
            "type": "string[]",
            "description": "File paths to diff; empty diffs all changed files.",
            "required": false
          },
          {
            "name": "sourceRevision",
            "label": "Source Revision",
            "type": "string",
            "description": "Source revision (empty = working tree).",
            "required": false
          },
          {
            "name": "targetRevision",
            "label": "Target Revision",
            "type": "string",
            "description": "Target revision (empty = working tree).",
            "required": false
          },
          {
            "name": "diff3",
            "label": "Diff3",
            "type": "boolean",
            "description": "Produce three-way merge output with conflict markers.",
            "required": false
          },
          {
            "name": "contextLines",
            "label": "Context Lines",
            "type": "number",
            "description": "Number of unchanged context lines per hunk.",
            "required": false
          },
          {
            "name": "ignoreWhitespaceEol",
            "label": "Ignore Whitespace EOL",
            "type": "boolean",
            "description": "Treat lines that differ only in trailing whitespace as equal.",
            "required": false
          },
          {
            "name": "ignoreWhitespaceInline",
            "label": "Ignore Whitespace Inline",
            "type": "boolean",
            "description": "Collapse runs of internal whitespace to a single space for comparison.",
            "required": false
          }
        ]
      },
      {
        "id": "file.dirty",
        "op": "dirty",
        "label": "File: Mark Dirty",
        "description": "Mark one or more paths as dirty (locally modified) so they are picked up by the next commit.",
        "command": "file_dirty",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "paths",
            "label": "Paths",
            "type": "string[]",
            "description": "Paths to mark as dirty (one per line).",
            "required": true
          }
        ]
      },
      {
        "id": "file.dirty_copy",
        "op": "dirty_copy",
        "label": "File: Dirty Copy",
        "description": "Stage a file copy without touching the filesystem. Creates a DirtyCopy node.",
        "command": "file_dirty_copy",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "fromPath",
            "label": "From Path",
            "type": "string",
            "description": "Source path of the file to copy.",
            "required": true
          },
          {
            "name": "toPath",
            "label": "To Path",
            "type": "string",
            "description": "Destination path for the copy.",
            "required": true
          }
        ]
      },
      {
        "id": "file.dirty_move",
        "op": "dirty_move",
        "label": "File: Dirty Move",
        "description": "Mark a file as moved in the staging area.",
        "command": "file_dirty_move",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "fromPath",
            "label": "From Path",
            "type": "string",
            "description": "Original path of the file to move.",
            "required": true
          },
          {
            "name": "toPath",
            "label": "To Path",
            "type": "string",
            "description": "New destination path.",
            "required": true
          }
        ]
      },
      {
        "id": "file.dump",
        "op": "dump",
        "label": "File: Dump",
        "description": "Dump the binary content of a file by path or address.",
        "command": "file_dump",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "address",
            "label": "Address",
            "type": "string",
            "description": "",
            "required": false
          },
          {
            "name": "path",
            "label": "Path",
            "type": "string",
            "description": "",
            "required": false
          }
        ]
      },
      {
        "id": "file.hash",
        "op": "hash",
        "label": "File: Hash",
        "description": "Compute the BLAKE3 content hash and size of one or more files.",
        "command": "file_hash",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "paths",
            "label": "Paths",
            "type": "string[]",
            "description": "File paths to hash (relative to repository root).",
            "required": true
          }
        ]
      },
      {
        "id": "file.info",
        "op": "info",
        "label": "File: Info",
        "description": "Show metadata for files — size, hash, flags, and staging status.",
        "command": "file_info",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "paths",
            "label": "Paths",
            "type": "string[]",
            "description": "Repository-relative paths to query (one per line).",
            "required": true
          },
          {
            "name": "revision",
            "label": "Revision",
            "type": "string",
            "description": "Revision specifier to query (leave empty for working copy).",
            "required": false
          },
          {
            "name": "local",
            "label": "Include Local Info",
            "type": "boolean",
            "description": "Calculate the filtered local filesystem hash and size.",
            "required": false
          },
          {
            "name": "filtered",
            "label": "Include Filtered Size",
            "type": "boolean",
            "description": "Calculate the filtered repository size.",
            "required": false
          }
        ]
      },
      {
        "id": "file.metadata_list",
        "op": "metadata_list",
        "label": "File: List Metadata",
        "description": "List all metadata key/value pairs for a file at a given revision.",
        "command": "file_metadata_list",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "path",
            "label": "Path",
            "type": "string",
            "description": "Path to the file to list metadata for.",
            "required": true
          },
          {
            "name": "revision",
            "label": "Revision",
            "type": "string",
            "description": "Revision to query; leave empty for the current revision.",
            "required": false
          }
        ]
      },
      {
        "id": "file.obliterate",
        "op": "obliterate",
        "label": "File: Obliterate",
        "description": "Permanently remove a file's content at a specific address from the store. This is irreversible.",
        "command": "file_obliterate",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "path",
            "label": "Path",
            "type": "string",
            "description": "Repository path of the file to obliterate.",
            "required": true
          },
          {
            "name": "address",
            "label": "Address",
            "type": "string",
            "description": "Content address (hash) of the file content to obliterate.",
            "required": true
          }
        ]
      },
      {
        "id": "file.reset_to_last_merged",
        "op": "reset_to_last_merged",
        "label": "File: Reset to Last Merged",
        "description": "Reset one or more files to the state they were in at the last merged revision on a given branch.",
        "command": "file_reset_to_last_merged",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "paths",
            "label": "Paths",
            "type": "string[]",
            "description": "Repository-relative paths to reset. One path per line.",
            "required": true
          },
          {
            "name": "branch",
            "label": "Branch",
            "type": "string",
            "description": "Branch whose last merged revision to reset to.",
            "required": true
          },
          {
            "name": "purge",
            "label": "Purge untracked files",
            "type": "boolean",
            "description": "Whether to purge untracked files.",
            "required": false
          }
        ]
      },
      {
        "id": "file.stage",
        "op": "stage",
        "label": "File: Stage",
        "description": "Stage one or more paths for the next commit.",
        "command": "stage",
        "surface": "palette",
        "resultKind": "void",
        "args": [
          {
            "name": "paths",
            "label": "Paths",
            "type": "string[]",
            "description": "One path per line.",
            "required": true
          }
        ]
      },
      {
        "id": "file.unstage",
        "op": "unstage",
        "label": "File: Unstage",
        "description": "Remove one or more paths from the staged changeset.",
        "command": "unstage",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "paths",
            "label": "Paths",
            "type": "string[]",
            "description": "One path per line to unstage.",
            "required": true
          }
        ]
      },
      {
        "id": "file.write",
        "op": "write",
        "label": "File: Write",
        "description": "Write a file from the repository to a destination path on the filesystem.",
        "command": "file_write",
        "surface": "palette",
        "resultKind": "text",
        "args": [
          {
            "name": "address",
            "label": "Address",
            "type": "string",
            "description": "Content address to write; takes precedence over path when set.",
            "required": false
          },
          {
            "name": "path",
            "label": "Path",
            "type": "string",
            "description": "Repository-relative path to the file (used when address is empty).",
            "required": false
          },
          {
            "name": "revision",
            "label": "Revision",
            "type": "string",
            "description": "Revision of the file to write (used with path).",
            "required": false
          },
          {
            "name": "output",
            "label": "Output Path",
            "type": "string",
            "description": "Destination filesystem path to write the file to.",
            "required": true
          }
        ]
      }
    ]
  },
  {
    "domain": "layer",
    "blurb": "Compose content in layers — add, remove, and list them.",
    "ops": [
      {
        "id": "layer.add",
        "op": "add",
        "label": "Layer: Add",
        "description": "Mount a source repository as a layer inside the current repository at a target path.",
        "command": "layer_add",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "targetPath",
            "label": "Target path",
            "type": "string",
            "description": "Path in the current repository where the layer should be placed.",
            "required": true
          },
          {
            "name": "sourceRepository",
            "label": "Source repository",
            "type": "string",
            "description": "Repository to add as a layer (URL or repository id).",
            "required": true
          },
          {
            "name": "sourcePath",
            "label": "Source path",
            "type": "string",
            "description": "Path in the source repository where the layer should start. Leave empty for the repository root.",
            "required": false
          },
          {
            "name": "metadata",
            "label": "Metadata key",
            "type": "string",
            "description": "Metadata key used to match revisions between the repositories. Optional.",
            "required": false
          }
        ]
      }
    ]
  },
  {
    "domain": "link",
    "blurb": "Add, remove, update, and list the links that compose content.",
    "ops": [
      {
        "id": "link.add",
        "op": "add",
        "label": "Link: Add",
        "description": "Add a link to a remote repository at the specified path.",
        "command": "link_add",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "link",
            "label": "Link URL",
            "type": "string",
            "description": "URL or identifier of the repository to link.",
            "required": true
          },
          {
            "name": "linkPath",
            "label": "Link Path",
            "type": "string",
            "description": "Path within this repository where the link is added.",
            "required": true
          },
          {
            "name": "sourcePath",
            "label": "Source Path",
            "type": "string",
            "description": "Path within the linked repository to pull from. \"/\" means the root.",
            "required": false
          },
          {
            "name": "pin",
            "label": "Pin",
            "type": "string",
            "description": "Branch or revision to pin the link at.",
            "required": false
          },
          {
            "name": "disableBranching",
            "label": "Disable Branching",
            "type": "boolean",
            "description": "Disable automatic branch creation in the linked repository.",
            "required": false
          }
        ]
      },
      {
        "id": "link.remove",
        "op": "remove",
        "label": "Link: Remove",
        "description": "Remove a link from the repository at the specified path.",
        "command": "link_remove",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "linkPath",
            "label": "Link Path",
            "type": "string",
            "description": "Path within this repository where the link to remove is located.",
            "required": true
          }
        ]
      }
    ]
  },
  {
    "domain": "lock",
    "blurb": "Advisory per-file locks for unmergeable binary assets — acquire, release, and see who holds what.",
    "ops": [
      {
        "id": "lock.file_acquire",
        "op": "file_acquire",
        "label": "Lock: Acquire Files",
        "description": "Acquire exclusive locks on one or more files for the current user.",
        "command": "lock_file_acquire",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "paths",
            "label": "Paths",
            "type": "string[]",
            "description": "File paths to lock, one per line.",
            "required": true
          },
          {
            "name": "branch",
            "label": "Branch",
            "type": "string",
            "description": "Branch to acquire locks on; leave empty for current branch.",
            "required": false
          }
        ]
      },
      {
        "id": "lock.file_acquire_as_owner",
        "op": "file_acquire_as_owner",
        "label": "Lock: Acquire Files as Owner",
        "description": "Acquire exclusive file locks on behalf of another user (admin operation).",
        "command": "lock_file_acquire_as_owner",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "paths",
            "label": "Paths",
            "type": "string[]",
            "description": "File paths to lock, one per line.",
            "required": true
          },
          {
            "name": "branch",
            "label": "Branch",
            "type": "string",
            "description": "Branch to acquire locks on; leave empty for current branch.",
            "required": false
          },
          {
            "name": "owner",
            "label": "Owner",
            "type": "string",
            "description": "User ID of the lock owner.",
            "required": true
          }
        ]
      },
      {
        "id": "lock.file_query",
        "op": "file_query",
        "label": "Lock: Query",
        "description": "List file locks on a branch, optionally filtered by owner or path.",
        "command": "lock_file_query",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "branch",
            "label": "Branch",
            "type": "string",
            "description": "Branch to query locks on; leave empty for current branch.",
            "required": false
          },
          {
            "name": "owner",
            "label": "Owner",
            "type": "string",
            "description": "Filter by lock owner; leave empty for all owners.",
            "required": false
          },
          {
            "name": "path",
            "label": "Path",
            "type": "string",
            "description": "Filter by path prefix; leave empty for all paths.",
            "required": false
          }
        ]
      },
      {
        "id": "lock.file_release",
        "op": "file_release",
        "label": "Lock: Release Files",
        "description": "Release exclusive file locks for the specified paths.",
        "command": "lock_file_release",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "paths",
            "label": "Paths",
            "type": "string[]",
            "description": "File paths to unlock, one per line.",
            "required": true
          },
          {
            "name": "branch",
            "label": "Branch",
            "type": "string",
            "description": "Branch the locks were acquired on; leave empty for current branch.",
            "required": false
          },
          {
            "name": "owner",
            "label": "Owner",
            "type": "string",
            "description": "Lock owner name.",
            "required": true
          },
          {
            "name": "ownerId",
            "label": "Owner ID",
            "type": "string",
            "description": "Lock owner ID.",
            "required": true
          }
        ]
      },
      {
        "id": "lock.file_status",
        "op": "file_status",
        "label": "Lock: File Status",
        "description": "Check the lock status of one or more files — shows owner and lock time.",
        "command": "lock_file_status",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "paths",
            "label": "Paths",
            "type": "string[]",
            "description": "File paths to check, one per line.",
            "required": true
          },
          {
            "name": "branch",
            "label": "Branch",
            "type": "string",
            "description": "Branch to check locks on; leave empty for current branch.",
            "required": false
          }
        ]
      },
      {
        "id": "lock.request_checkin",
        "op": "request_checkin",
        "label": "Lock: Request Check-In",
        "description": "Ask the holder of a locked file to check it in. They get a tray notification and an inbox entry with Release / Dismiss.",
        "command": "lock_request_checkin",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "path",
            "label": "File path",
            "type": "string",
            "description": "The locked file you want released.",
            "required": true
          },
          {
            "name": "branch",
            "label": "Branch",
            "type": "string",
            "description": "Branch the lock is on; leave empty for the current branch.",
            "required": false
          },
          {
            "name": "from",
            "label": "Your name",
            "type": "string",
            "description": "Who the request is from (shown to the holder).",
            "required": true
          },
          {
            "name": "holder",
            "label": "Holder",
            "type": "string",
            "description": "Display name of the current lock holder.",
            "required": true
          },
          {
            "name": "toUserId",
            "label": "Holder user ID",
            "type": "string",
            "description": "User id of the holder (from the lock's owner field).",
            "required": true
          },
          {
            "name": "note",
            "label": "Note",
            "type": "string",
            "description": "Optional message to the holder.",
            "required": false
          }
        ]
      }
    ]
  },
  {
    "domain": "repository",
    "blurb": "Open, create, clone, and administer a repository: status, info, flush, garbage-collect, verify, and metadata.",
    "ops": [
      {
        "id": "repository.clone",
        "op": "clone",
        "label": "Repository: Clone",
        "description": "Clone a remote repository to a local directory.",
        "command": "repository_clone",
        "surface": "palette",
        "resultKind": "void",
        "args": [
          {
            "name": "url",
            "label": "Repository URL",
            "type": "string",
            "description": "",
            "required": true
          },
          {
            "name": "dest",
            "label": "Destination",
            "type": "string",
            "description": "",
            "required": true
          }
        ]
      },
      {
        "id": "repository.clone_url",
        "op": "clone_url",
        "label": "Repository: Clone from URL",
        "description": "Clone a remote repository URL into a local destination directory and open it.",
        "command": "clone",
        "surface": "palette",
        "resultKind": "void",
        "args": [
          {
            "name": "url",
            "label": "Remote URL",
            "type": "string",
            "description": "URL of the remote repository to clone.",
            "required": true
          },
          {
            "name": "dest",
            "label": "Destination",
            "type": "string",
            "description": "Local directory to clone into.",
            "required": true
          }
        ]
      },
      {
        "id": "repository.config_get",
        "op": "config_get",
        "label": "Repository: Get Config",
        "description": "Read a configuration value from the repository config.",
        "command": "repository_config_get",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "key",
            "label": "Config Key",
            "type": "string",
            "description": "The configuration key to read (e.g. remote_url, identity).",
            "required": true
          }
        ]
      },
      {
        "id": "repository.create",
        "op": "create",
        "label": "Repository: Create",
        "description": "Create a new local repository.",
        "command": "repository_create",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "repositoryUrl",
            "label": "Repository URL",
            "type": "string",
            "description": "URL for the new repository (e.g. lore://localhost/<name>).",
            "required": true
          },
          {
            "name": "description",
            "label": "Description",
            "type": "string",
            "description": "Optional description for the repository.",
            "required": false
          },
          {
            "name": "id",
            "label": "ID",
            "type": "string",
            "description": "Optional repository UUID; leave empty to auto-generate.",
            "required": false
          },
          {
            "name": "useSharedStore",
            "label": "Use Shared Store",
            "type": "boolean",
            "description": "Use the shared store instead of a local immutable store.",
            "required": false
          },
          {
            "name": "sharedStorePath",
            "label": "Shared Store Path",
            "type": "string",
            "description": "Path for the shared store; leave empty for the default.",
            "required": false
          }
        ]
      },
      {
        "id": "repository.create_with_metadata",
        "op": "create_with_metadata",
        "label": "Repository: Create with Metadata",
        "description": "Create a new repository with explicit creator and timestamp metadata.",
        "command": "repository_create_with_metadata",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "repositoryUrl",
            "label": "Repository URL",
            "type": "string",
            "description": "URL for the new repository (e.g. lore://localhost/<name>).",
            "required": true
          },
          {
            "name": "creator",
            "label": "Creator",
            "type": "string",
            "description": "Username or identifier of the repository creator.",
            "required": true
          },
          {
            "name": "created",
            "label": "Created (epoch ms)",
            "type": "number",
            "description": "Creation timestamp in milliseconds since Unix epoch.",
            "required": true
          },
          {
            "name": "description",
            "label": "Description",
            "type": "string",
            "description": "Optional description for the repository.",
            "required": false
          },
          {
            "name": "id",
            "label": "ID",
            "type": "string",
            "description": "Optional repository UUID; leave empty to auto-generate.",
            "required": false
          },
          {
            "name": "useSharedStore",
            "label": "Use Shared Store",
            "type": "boolean",
            "description": "Use the shared store instead of a local immutable store.",
            "required": false
          },
          {
            "name": "sharedStorePath",
            "label": "Shared Store Path",
            "type": "string",
            "description": "Path for the shared store; leave empty for the default.",
            "required": false
          }
        ]
      },
      {
        "id": "repository.delete",
        "op": "delete",
        "label": "Repository: Delete",
        "description": "Delete a repository by URL.",
        "command": "repository_delete",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "repositoryUrl",
            "label": "Repository URL",
            "type": "string",
            "description": "URL of the repository to delete.",
            "required": true
          }
        ]
      },
      {
        "id": "repository.dump",
        "op": "dump",
        "label": "Repository: Dump Tree",
        "description": "Dump the repository tree structure at a given revision and path.",
        "command": "repository_dump",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "revision",
            "label": "Revision",
            "type": "string",
            "description": "Revision to dump; leave empty for the current revision.",
            "required": false
          },
          {
            "name": "path",
            "label": "Path",
            "type": "string",
            "description": "Repository-relative path to dump from; leave empty for the root.",
            "required": false
          },
          {
            "name": "maxDepth",
            "label": "Max Depth",
            "type": "number",
            "description": "Maximum tree traversal depth; 0 means unlimited.",
            "required": false
          }
        ]
      },
      {
        "id": "repository.flush",
        "op": "flush",
        "label": "Repository: Flush",
        "description": "Flush pending repository data to persistent storage.",
        "command": "repository_flush",
        "surface": "palette",
        "resultKind": "json",
        "args": []
      },
      {
        "id": "repository.gc",
        "op": "gc",
        "label": "Repository: Garbage Collect",
        "description": "Run garbage collection on the repository to clean up unreferenced data.",
        "command": "repository_gc",
        "surface": "palette",
        "resultKind": "json",
        "args": []
      },
      {
        "id": "repository.info",
        "op": "info",
        "label": "Repository: Info",
        "description": "Retrieve metadata about a repository (name, URL, default branch, creator).",
        "command": "repository_info",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "repositoryUrl",
            "label": "Repository URL",
            "type": "string",
            "description": "URL of the repository to query; leave empty to use the current repository.",
            "required": false
          }
        ]
      },
      {
        "id": "repository.instance_list",
        "op": "instance_list",
        "label": "Repository: List Instances",
        "description": "List all repository instances (working copies) in the shared store.",
        "command": "repository_instance_list",
        "surface": "palette",
        "resultKind": "json",
        "args": []
      },
      {
        "id": "repository.instance_prune",
        "op": "instance_prune",
        "label": "Repository: Prune Stale Instances",
        "description": "Remove stale repository instances (working copies whose filesystem paths no longer exist) from the shared store.",
        "command": "repository_instance_prune",
        "surface": "palette",
        "resultKind": "json",
        "args": []
      },
      {
        "id": "repository.list",
        "op": "list",
        "label": "Repository: List",
        "description": "List all repositories available at a remote URL.",
        "command": "repository_list",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "url",
            "label": "Remote URL",
            "type": "string",
            "description": "The lore:// URL to query for available repositories.",
            "required": true
          }
        ]
      },
      {
        "id": "repository.metadata_clear",
        "op": "metadata_clear",
        "label": "Repository: Clear Metadata",
        "description": "Clear user-defined metadata keys from the repository (empty list clears all).",
        "command": "repository_metadata_clear",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "keys",
            "label": "Keys",
            "type": "string[]",
            "description": "Metadata keys to clear; leave empty to clear all user-defined keys.",
            "required": false
          }
        ]
      },
      {
        "id": "repository.metadata_get",
        "op": "metadata_get",
        "label": "Repository: Get Metadata",
        "description": "Read metadata entries from the repository (empty key returns all).",
        "command": "repository_metadata_get",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "key",
            "label": "Key",
            "type": "string",
            "description": "Metadata key to read; leave empty to return all entries.",
            "required": false
          }
        ]
      },
      {
        "id": "repository.metadata_set",
        "op": "metadata_set",
        "label": "Repository: Set Metadata",
        "description": "Set metadata key-value pairs on the repository.",
        "command": "repository_metadata_set",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "keys",
            "label": "Keys",
            "type": "string[]",
            "description": "Metadata keys to set (one per line).",
            "required": true
          },
          {
            "name": "values",
            "label": "Values",
            "type": "string[]",
            "description": "Values for each key (one per line, parallel to keys).",
            "required": true
          },
          {
            "name": "formats",
            "label": "Formats",
            "type": "string[]",
            "description": "Format for each key: \"string\", \"numeric\", or \"binary\". Defaults to \"string\" for missing entries.",
            "required": false
          }
        ]
      },
      {
        "id": "repository.push",
        "op": "push",
        "label": "Repository: Push",
        "description": "Push local commits on the current branch to the remote.",
        "command": "push",
        "surface": "palette",
        "resultKind": "void",
        "args": []
      },
      {
        "id": "repository.release",
        "op": "release",
        "label": "Repository: Release",
        "description": "Release the repository and free associated resources.",
        "command": "repository_release",
        "surface": "palette",
        "resultKind": "json",
        "args": []
      },
      {
        "id": "repository.repository_update_path",
        "op": "repository_update_path",
        "label": "Repository: Update Path",
        "description": "Update the stored repository path to match the current working directory.",
        "command": "repository_update_path",
        "surface": "palette",
        "resultKind": "json",
        "args": []
      },
      {
        "id": "repository.status",
        "op": "status",
        "label": "Repository: Status",
        "description": "Show working-tree status — branch, revision, changes, ahead/behind.",
        "command": "status",
        "surface": "palette",
        "resultKind": "json",
        "args": []
      },
      {
        "id": "repository.store_immutable_query",
        "op": "store_immutable_query",
        "label": "Repository: Query Immutable Store",
        "description": "Query the immutable store for a fragment by address.",
        "command": "repository_store_immutable_query",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "address",
            "label": "Fragment Address",
            "type": "string",
            "description": "The fragment address (hash) to look up in the store.",
            "required": true
          },
          {
            "name": "recurse",
            "label": "Recurse",
            "type": "boolean",
            "description": "Recursively query sub-fragments.",
            "required": false
          }
        ]
      },
      {
        "id": "repository.sync",
        "op": "sync",
        "label": "Repository: Sync",
        "description": "Sync the current repository with its remote, pulling and applying the latest changes.",
        "command": "sync",
        "surface": "palette",
        "resultKind": "void",
        "args": []
      },
      {
        "id": "repository.verify_fragment",
        "op": "verify_fragment",
        "label": "Repository: Verify Fragment",
        "description": "Verify the integrity of a specific fragment by hash; optionally heal corruption.",
        "command": "repository_verify_fragment",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "hash",
            "label": "Fragment Hash",
            "type": "string",
            "description": "The fragment hash (hex string) to verify.",
            "required": true
          },
          {
            "name": "context",
            "label": "Context",
            "type": "string",
            "description": "Optional context filter; leave empty to match any context.",
            "required": false
          },
          {
            "name": "heal",
            "label": "Heal",
            "type": "boolean",
            "description": "When true, attempt to heal detected corruption.",
            "required": false
          }
        ]
      },
      {
        "id": "repository.verify_state",
        "op": "verify_state",
        "label": "Repository: Verify State",
        "description": "Verify repository integrity; optionally heal detected inconsistencies. Returns fragment-level verification events and a typed summary.",
        "command": "repository_verify_state",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "path",
            "label": "Path",
            "type": "string",
            "description": "Repository-relative path to verify; empty verifies the whole repository.",
            "required": false
          },
          {
            "name": "heal",
            "label": "Heal",
            "type": "boolean",
            "description": "When true, attempt to heal detected inconsistencies.",
            "required": false
          }
        ]
      }
    ]
  },
  {
    "domain": "revision",
    "blurb": "The commit surface: commit, amend, diff, inspect, find, revert, restore, and sync revisions.",
    "ops": [
      {
        "id": "revision.activity_report",
        "op": "activity_report",
        "label": "Revision: Activity Report (Premium)",
        "description": "Who-did-what-when rollup over the revision history — powers the premium Reporting & Insights add-on.",
        "command": "revision_activity_report",
        "surface": "panel",
        "resultKind": "json",
        "args": [
          {
            "name": "revision",
            "label": "Revision",
            "type": "string",
            "description": "Start from this revision; empty for current HEAD.",
            "required": false
          },
          {
            "name": "branch",
            "label": "Branch",
            "type": "string",
            "description": "Restrict to this branch; empty for current.",
            "required": false
          },
          {
            "name": "length",
            "label": "Max revisions",
            "type": "number",
            "description": "Maximum number of revisions to scan; 0 for unlimited.",
            "required": false
          },
          {
            "name": "author",
            "label": "Contributor",
            "type": "string",
            "description": "Only include revisions by an author whose name contains this substring.",
            "required": false
          },
          {
            "name": "dateFrom",
            "label": "From (Unix seconds)",
            "type": "number",
            "description": "Only include revisions at or after this timestamp; 0 = unbounded.",
            "required": false
          },
          {
            "name": "dateTo",
            "label": "To (Unix seconds)",
            "type": "number",
            "description": "Only include revisions at or before this timestamp; 0 = unbounded.",
            "required": false
          },
          {
            "name": "filePath",
            "label": "File path",
            "type": "string",
            "description": "Only include revisions that touched this file path.",
            "required": false
          }
        ]
      },
      {
        "id": "revision.amend",
        "op": "amend",
        "label": "Revision: Amend",
        "description": "Amend the most recent revision's commit message.",
        "command": "revision_amend",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "message",
            "label": "Message",
            "type": "string",
            "description": "",
            "required": true
          }
        ]
      },
      {
        "id": "revision.cherry_pick_restart",
        "op": "cherry_pick_restart",
        "label": "Revision: Cherry-Pick Restart",
        "description": "Restart resolution for specified paths during an in-progress cherry-pick conflict.",
        "command": "revision_cherry_pick_restart",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "paths",
            "label": "Paths",
            "type": "string[]",
            "description": "Repository-relative paths to re-materialise for resolution (one per line).",
            "required": true
          }
        ]
      },
      {
        "id": "revision.commit",
        "op": "commit",
        "label": "Revision: Commit",
        "description": "Commit the staged changes with a message.",
        "command": "commit",
        "surface": "palette",
        "resultKind": "text",
        "args": [
          {
            "name": "message",
            "label": "Message",
            "type": "string",
            "description": "",
            "required": true
          }
        ]
      },
      {
        "id": "revision.commit_with_metadata",
        "op": "commit_with_metadata",
        "label": "Revision: Commit with Metadata",
        "description": "Commit staged changes with attached metadata key-value pairs.",
        "command": "revision_commit_with_metadata",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "message",
            "label": "Message",
            "type": "string",
            "description": "Commit message describing the revision.",
            "required": true
          },
          {
            "name": "keys",
            "label": "Keys",
            "type": "string[]",
            "description": "One metadata key per line. Must match values/formats length.",
            "required": false
          },
          {
            "name": "values",
            "label": "Values",
            "type": "string[]",
            "description": "One value per line. Must match keys/formats length.",
            "required": false
          },
          {
            "name": "formats",
            "label": "Format Types",
            "type": "string[]",
            "description": "One format per line (binary, numeric, or string). Must match keys/values length.",
            "required": false
          }
        ]
      },
      {
        "id": "revision.diff",
        "op": "diff",
        "label": "Revision: Diff",
        "description": "Show file-level differences between two revisions.",
        "command": "revision_diff",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "revisionSource",
            "label": "Source Revision",
            "type": "string",
            "description": "Revision to diff from.",
            "required": true
          },
          {
            "name": "revisionTarget",
            "label": "Target Revision",
            "type": "string",
            "description": "Revision to diff to; empty for current working state.",
            "required": false
          },
          {
            "name": "paths",
            "label": "Paths",
            "type": "string[]",
            "description": "Restrict diff to these repository-relative paths; empty for all files.",
            "required": false
          }
        ]
      },
      {
        "id": "revision.find",
        "op": "find",
        "label": "Revision: Find",
        "description": "Find revisions by metadata key/value or revision number, searching local and remote stores.",
        "command": "revision_find",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "key",
            "label": "Metadata Key",
            "type": "string",
            "description": "Search by this metadata key (e.g. 'tag', 'author'). Leave empty to search by revision number.",
            "required": false
          },
          {
            "name": "value",
            "label": "Metadata Value",
            "type": "string",
            "description": "Match this value for the given key.",
            "required": false
          },
          {
            "name": "number",
            "label": "Revision Number",
            "type": "number",
            "description": "Search by revision number when key is empty.",
            "required": false
          }
        ]
      },
      {
        "id": "revision.find_local",
        "op": "find_local",
        "label": "Revision: Find Local",
        "description": "Find revisions by metadata key/value or revision number (local only).",
        "command": "revision_find_local",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "key",
            "label": "Metadata Key",
            "type": "string",
            "description": "Metadata key to search for; leave empty to search by number.",
            "required": false
          },
          {
            "name": "value",
            "label": "Metadata Value",
            "type": "string",
            "description": "Value to match against the metadata key.",
            "required": false
          },
          {
            "name": "number",
            "label": "Revision Number",
            "type": "number",
            "description": "Revision number to find; used when key is empty. 0 disables.",
            "required": false
          }
        ]
      },
      {
        "id": "revision.history",
        "op": "history",
        "label": "Revision: History",
        "description": "Show revision history for the current branch or a specified revision.",
        "command": "revision_history",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "revision",
            "label": "Revision",
            "type": "string",
            "description": "Start from this revision; empty for current.",
            "required": false
          },
          {
            "name": "branch",
            "label": "Branch",
            "type": "string",
            "description": "Restrict to this branch; empty for current.",
            "required": false
          },
          {
            "name": "date",
            "label": "Date",
            "type": "number",
            "description": "Stop at revisions created before this Unix timestamp; 0 disables.",
            "required": false
          },
          {
            "name": "length",
            "label": "Length",
            "type": "number",
            "description": "Maximum number of revisions to return; 0 for unlimited.",
            "required": false
          },
          {
            "name": "onlyBranch",
            "label": "Only Branch",
            "type": "boolean",
            "description": "Stop when reaching a different branch.",
            "required": false
          }
        ]
      },
      {
        "id": "revision.info",
        "op": "info",
        "label": "Revision: Info",
        "description": "Show metadata and file changes for a revision.",
        "command": "revision_info",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "revision",
            "label": "Revision",
            "type": "string",
            "description": "Revision to inspect; empty for current.",
            "required": false
          },
          {
            "name": "delta",
            "label": "Include Delta",
            "type": "boolean",
            "description": "Include per-file changes against the parent revision.",
            "required": false
          },
          {
            "name": "metadata",
            "label": "Include Metadata",
            "type": "boolean",
            "description": "Include key/value metadata entries.",
            "required": false
          }
        ]
      },
      {
        "id": "revision.log",
        "op": "log",
        "label": "Revision: Log",
        "description": "List the most recent revisions on the current branch, newest first.",
        "command": "log",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "limit",
            "label": "Limit",
            "type": "number",
            "description": "Maximum number of revisions to return.",
            "required": true
          }
        ]
      },
      {
        "id": "revision.metadata_clear",
        "op": "metadata_clear",
        "label": "Revision: Metadata Clear",
        "description": "Clear all metadata from the current revision.",
        "command": "revision_metadata_clear",
        "surface": "palette",
        "resultKind": "json",
        "args": []
      },
      {
        "id": "revision.revert",
        "op": "revert",
        "label": "Revision: Revert",
        "description": "Revert the working directory to a specified revision by applying the inverse of its changes.",
        "command": "revision_revert_local",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "revision",
            "label": "Revision",
            "type": "string",
            "description": "",
            "required": true
          },
          {
            "name": "message",
            "label": "Message",
            "type": "string",
            "description": "Commit message for the auto-commit when no conflicts arise.",
            "required": false
          },
          {
            "name": "noCommit",
            "label": "No Commit",
            "type": "boolean",
            "description": "Skip auto-commit even if there are no conflicts.",
            "required": false
          }
        ]
      },
      {
        "id": "revision.revert_abort",
        "op": "revert_abort",
        "label": "Revision: Abort Revert",
        "description": "Abort an in-progress revert operation and restore the working directory.",
        "command": "revision_revert_abort",
        "surface": "palette",
        "resultKind": "json",
        "args": []
      },
      {
        "id": "revision.revert_local",
        "op": "revert_local",
        "label": "Revision: Revert Local",
        "description": "Revert the working directory to a specified revision by applying the inverse of its changes.",
        "command": "revision_revert_local",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "revision",
            "label": "Revision",
            "type": "string",
            "description": "",
            "required": true
          },
          {
            "name": "message",
            "label": "Message",
            "type": "string",
            "description": "Commit message for the auto-commit when no conflicts arise.",
            "required": false
          },
          {
            "name": "noCommit",
            "label": "No Auto-Commit",
            "type": "boolean",
            "description": "Skip auto-commit even if there are no conflicts.",
            "required": false
          }
        ]
      },
      {
        "id": "revision.revert_resolve",
        "op": "revert_resolve",
        "label": "Revision: Revert Resolve",
        "description": "Mark conflicted paths as resolved during an in-progress revert.",
        "command": "revision_revert_resolve",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "paths",
            "label": "Paths",
            "type": "string[]",
            "description": "Repository-relative paths to mark as resolved.",
            "required": true
          }
        ]
      },
      {
        "id": "revision.revert_resolve_mine",
        "op": "revert_resolve_mine",
        "label": "Revision: Revert Resolve Mine",
        "description": "Resolve revert conflicts on the given paths by keeping the local (mine) version.",
        "command": "revision_revert_resolve_mine",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "paths",
            "label": "Paths",
            "type": "string[]",
            "description": "Repository-relative paths to resolve in favor of mine (local).",
            "required": true
          }
        ]
      },
      {
        "id": "revision.sync",
        "op": "sync",
        "label": "Revision: Sync",
        "description": "Sync the working tree to a target revision, optionally resetting and pulling dependencies.",
        "command": "revision_sync",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "revision",
            "label": "Revision",
            "type": "string",
            "description": "Target revision to sync to; empty syncs to the latest.",
            "required": false
          },
          {
            "name": "forwardChanges",
            "label": "Forward changes",
            "type": "boolean",
            "description": "Carry local changes forward across the sync.",
            "required": false
          },
          {
            "name": "reset",
            "label": "Reset",
            "type": "boolean",
            "description": "Discard local changes and reset to the target revision.",
            "required": false
          },
          {
            "name": "rootFiles",
            "label": "Root files",
            "type": "string[]",
            "description": "Restrict the sync to these root files (one per line).",
            "required": false
          },
          {
            "name": "dependencyTags",
            "label": "Dependency tags",
            "type": "string[]",
            "description": "Dependency tags to include when syncing (one per line).",
            "required": false
          },
          {
            "name": "dependencyRecursive",
            "label": "Recursive dependencies",
            "type": "boolean",
            "description": "Resolve dependencies recursively.",
            "required": false
          },
          {
            "name": "dependencyDepthLimit",
            "label": "Dependency depth limit",
            "type": "number",
            "description": "Maximum depth when resolving dependencies (0 = unlimited).",
            "required": false
          }
        ]
      }
    ]
  },
  {
    "domain": "service",
    "blurb": "Start and stop the lore background service.",
    "ops": [
      {
        "id": "service.host_server_start",
        "op": "host_server_start",
        "label": "Host Server: Start",
        "description": "Launch a real Lore server (loreserver) over a local store on 127.0.0.1. Returns the lore:// URL to give to clients.",
        "command": "host_server_start",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "storeDir",
            "label": "Store directory",
            "type": "string",
            "description": "Directory backing the served stores. Use the same shared-store path your repository was created in.",
            "required": true
          },
          {
            "name": "port",
            "label": "Port",
            "type": "number",
            "description": "QUIC/gRPC port. HTTP is served on port + 2. Defaults to 41337.",
            "required": false
          },
          {
            "name": "repositoryName",
            "label": "Repository name",
            "type": "string",
            "description": "Optional. Embedded in the advertised lore://host:port/<name> URL clients clone.",
            "required": false
          }
        ]
      },
      {
        "id": "service.host_server_status",
        "op": "host_server_status",
        "label": "Host Server: Status",
        "description": "Show whether a hosted Lore server is running, with its pid, port, and lore:// URL.",
        "command": "host_server_status",
        "surface": "palette",
        "resultKind": "json",
        "args": []
      },
      {
        "id": "service.host_server_stop",
        "op": "host_server_stop",
        "label": "Host Server: Stop",
        "description": "Stop the hosted Lore server (loreserver) started from the GUI.",
        "command": "host_server_stop",
        "surface": "palette",
        "resultKind": "json",
        "args": []
      },
      {
        "id": "service.lan_discover_browse",
        "op": "lan_discover_browse",
        "label": "Discover Servers on Network",
        "description": "Scan the local network for lore servers (mDNS) and list any found, with the lore:// URL to connect. Open-core; the manual server URL always works too.",
        "command": "lan_discover_browse",
        "surface": "palette",
        "resultKind": "json",
        "args": []
      },
      {
        "id": "service.start",
        "op": "start",
        "label": "Service: Start",
        "description": "Start the Lore service process for the current repository.",
        "command": "service_start",
        "surface": "palette",
        "resultKind": "void",
        "args": []
      },
      {
        "id": "service.stop",
        "op": "stop",
        "label": "Service: Stop",
        "description": "Stop the Lore service process for the current repository (or all repositories).",
        "command": "service_stop",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "all",
            "label": "All repositories",
            "type": "boolean",
            "description": "Stop the service for all repositories rather than just the current one.",
            "required": false
          }
        ]
      }
    ]
  },
  {
    "domain": "shared_store",
    "blurb": "Create and configure a shared store that multiple repositories read from.",
    "ops": [
      {
        "id": "shared_store.create",
        "op": "create",
        "label": "Shared Store: Create",
        "description": "Create a shared store on disk that repositories can use as a common content cache.",
        "command": "shared_store_create",
        "surface": "panel",
        "resultKind": "text",
        "args": [
          {
            "name": "path",
            "label": "Store path",
            "type": "string",
            "description": "Filesystem path where the shared store is created.",
            "required": true
          }
        ]
      },
      {
        "id": "shared_store.info",
        "op": "info",
        "label": "Shared Store: Info",
        "description": "List the configured shared stores — their URLs, paths, existence, and auto-use setting.",
        "command": "shared_store_info",
        "surface": "panel",
        "resultKind": "json",
        "args": []
      },
      {
        "id": "shared_store.set_use_automatically",
        "op": "set_use_automatically",
        "label": "Shared Store: Set Auto-Use",
        "description": "Enable or disable automatic use of the configured default shared store for repositories.",
        "command": "shared_store_set_use_automatically",
        "surface": "panel",
        "resultKind": "void",
        "args": [
          {
            "name": "enabled",
            "label": "Use automatically",
            "type": "boolean",
            "description": "When on, the default shared store is consulted automatically.",
            "required": false
          }
        ]
      }
    ]
  },
  {
    "domain": "storage",
    "blurb": "Content-addressed storage backends — open/close/flush a backend and put, get, copy, or obliterate fragments.",
    "ops": [
      {
        "id": "storage.close",
        "op": "close",
        "label": "Storage: Close",
        "description": "Release an open storage handle, draining in-flight ops and flushing pending writes.",
        "command": "storage_close",
        "surface": "panel",
        "resultKind": "json",
        "args": [
          {
            "name": "handle",
            "label": "Handle",
            "type": "number",
            "description": "Handle id returned by Storage: Open.",
            "required": true
          }
        ]
      },
      {
        "id": "storage.copy",
        "op": "copy",
        "label": "Storage: Copy",
        "description": "Copy a fragment from one partition to another in the same store, preserving its content hash.",
        "command": "storage_copy",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "handle",
            "label": "Handle",
            "type": "number",
            "description": "Handle id returned by Storage: Open.",
            "required": true
          },
          {
            "name": "sourcePartition",
            "label": "Source partition",
            "type": "string",
            "description": "32-hex-char source partition namespace.",
            "required": true
          },
          {
            "name": "sourceAddress",
            "label": "Source address",
            "type": "string",
            "description": "Content address of the fragment to copy (<hash> or <hash>-<context>).",
            "required": true
          },
          {
            "name": "targetPartition",
            "label": "Target partition",
            "type": "string",
            "description": "32-hex-char destination partition namespace.",
            "required": true
          },
          {
            "name": "targetContext",
            "label": "Target context",
            "type": "string",
            "description": "Optional 32-hex-char dedup context for the destination. Empty uses the zero context.",
            "required": false
          }
        ]
      },
      {
        "id": "storage.flush",
        "op": "flush",
        "label": "Storage: Flush",
        "description": "Flush pending writes through an open storage handle, fsyncing disk-backed stores.",
        "command": "storage_flush",
        "surface": "panel",
        "resultKind": "json",
        "args": [
          {
            "name": "handle",
            "label": "Handle",
            "type": "number",
            "description": "Handle id returned by Storage: Open.",
            "required": true
          }
        ]
      },
      {
        "id": "storage.get",
        "op": "get",
        "label": "Storage: Get",
        "description": "Read a content-addressed buffer from the open store using a session key returned by a prior Storage: Put.",
        "command": "storage_get",
        "surface": "panel",
        "resultKind": "json",
        "args": [
          {
            "name": "key",
            "label": "Key",
            "type": "string",
            "description": "Session key returned by a prior Storage: Put call.",
            "required": true
          }
        ]
      },
      {
        "id": "storage.get_metadata",
        "op": "get_metadata",
        "label": "Storage: Get Metadata",
        "description": "Fetch a fragment's metadata (flags, payload size, content size) by partition and address — no bytes transferred.",
        "command": "storage_get_metadata",
        "surface": "panel",
        "resultKind": "json",
        "args": [
          {
            "name": "handle",
            "label": "Handle",
            "type": "number",
            "description": "Handle id returned by Storage: Open.",
            "required": true
          },
          {
            "name": "partition",
            "label": "Partition",
            "type": "string",
            "description": "32-hex-char partition namespace (the zero partition is rejected).",
            "required": true
          },
          {
            "name": "address",
            "label": "Address",
            "type": "string",
            "description": "Content address: <hash> or <hash>-<context>.",
            "required": true
          }
        ]
      },
      {
        "id": "storage.open",
        "op": "open",
        "label": "Storage: Open",
        "description": "Open a content-addressed store (local path, remote URL, or in-memory) and return its handle.",
        "command": "storage_open_handle",
        "surface": "panel",
        "resultKind": "json",
        "args": [
          {
            "name": "repositoryPath",
            "label": "Repository path",
            "type": "string",
            "description": "Local lore repository to open. Leave empty for remote/in-memory.",
            "required": false
          },
          {
            "name": "remoteUrl",
            "label": "Remote URL",
            "type": "string",
            "description": "Remote store endpoint. Leave empty for a local-only store.",
            "required": false
          },
          {
            "name": "inMemory",
            "label": "In-memory store",
            "type": "boolean",
            "description": "Open a throwaway in-memory store (path and remote URL must be empty).",
            "required": false
          }
        ]
      },
      {
        "id": "storage.put",
        "op": "put",
        "label": "Storage: Put",
        "description": "Write a content-addressed buffer to an open store by key. The key lets you retrieve or obliterate the data later.",
        "command": "storage_put",
        "surface": "palette",
        "resultKind": "void",
        "args": [
          {
            "name": "key",
            "label": "Key",
            "type": "string",
            "description": "Opaque label that correlates this write with a later get or obliterate.",
            "required": true
          },
          {
            "name": "data",
            "label": "Data (JSON byte array)",
            "type": "string",
            "description": "The bytes to store, as a JSON array of numbers (e.g. [72, 101, 108, 108, 111]).",
            "required": true
          }
        ]
      },
      {
        "id": "storage.put_file",
        "op": "put_file",
        "label": "Storage: Put File",
        "description": "Read a file from disk and store its contents in an open store, returning the content address.",
        "command": "storage_put_file",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "handle",
            "label": "Handle",
            "type": "number",
            "description": "Handle id returned by Storage: Open.",
            "required": true
          },
          {
            "name": "partition",
            "label": "Partition",
            "type": "string",
            "description": "32-hex-char partition namespace (the zero partition is rejected).",
            "required": true
          },
          {
            "name": "path",
            "label": "File path",
            "type": "string",
            "description": "Filesystem path of the file to read and store.",
            "required": true
          },
          {
            "name": "context",
            "label": "Context",
            "type": "string",
            "description": "Optional 32-hex-char dedup context. Empty uses the zero context.",
            "required": false
          },
          {
            "name": "remoteWrite",
            "label": "Remote write",
            "type": "boolean",
            "description": "Also push the fragment to the configured remote store.",
            "required": false
          },
          {
            "name": "localCache",
            "label": "Local cache priority",
            "type": "boolean",
            "description": "Tag the fragment for local-cache retention priority.",
            "required": false
          }
        ]
      },
      {
        "id": "storage.upload",
        "op": "upload",
        "label": "Storage: Upload",
        "description": "Push a locally-stored fragment to the remote attached to an open store (handle must have a remote configured).",
        "command": "storage_upload",
        "surface": "palette",
        "resultKind": "json",
        "args": [
          {
            "name": "handle",
            "label": "Handle",
            "type": "number",
            "description": "Handle id returned by Storage: Open (must have a remote configured).",
            "required": true
          },
          {
            "name": "partition",
            "label": "Partition",
            "type": "string",
            "description": "32-hex-char partition namespace of the local content.",
            "required": true
          },
          {
            "name": "address",
            "label": "Address",
            "type": "string",
            "description": "Content address to push (<hash> or <hash>-<context>).",
            "required": true
          }
        ]
      }
    ]
  }
];
